### ISSUE TITLE
Submit to MELPA

### ISSUE THREAD

**Issue by zeltak** [alphapapa/helm-org-rifle#1]
this is very cool! any chance it will be on melpa?

best and thx for your work

Z

**Comment by alphapapa** [comment]
Hey, thanks for your message.  Yeah, I just got https://github.com/alphapapa/org-bookmark-heading on MELPA, and I will probably submit this soon.  It's not perfect, but I think it's usable and useful enough to be worth it, so keep an eye out.  ;)

**Comment by alphapapa** [comment]
Steve [merged](https://github.com/melpa/melpa/pull/3716) it in record time!
