### ISSUE TITLE
Please test new timestamp-sorting code

### ISSUE THREAD

**Issue by alphapapa** [alphapapa/helm-org-rifle#11]
@zeltak @jonmoore @whacked Hi there, I have just pushed a new branch that lets you sort results by the latest timestamp in each node.  

https://github.com/alphapapa/helm-org-rifle/tree/sort-by-timestamp

It seems to be working but I would like it to get more testing before I release it.  If you have time, would you mind testing it out?  

1.  There are new commands: `helm-org-rifle-sort-by-latest-timestamp` and `helm-org-rifle-current-buffer-sort-by-latest-timestamp`.
2.  The regular commands can be run with a prefix to prompt for the sorting method, either `nil` (which is the order they appear in the file), or to sort by latest timestamp.  The sorting method persists.  This UI could be a bit nicer still.  Also, the prefix conflicts with using a prefix for running `helm-org-rifle-directories` recursively, so I'll have to figure out another way to do that.

Also, please let me know if you have any ideas for the best way to access the sorting feature.  The best way I've thought of would be to have a separate command to activate sorting which would present the different sorting options in a list with Helm and then activate the command.  Another possibility would be to use a hydra, but I'm not sure I want to add a dependency for that.

Thanks.  :)

**Comment by whacked** [comment]
Thanks for the update. I must admit helm-org-rifle has never made it into my regular workflow, but I started revisiting it about 2 weeks ago. I currently have `helm-org-rifle-20160420.818` installed from ELPA and I have only been using vanilla `M-x helm-org-rifle`.

What's the passing criteria of this test, or is this for UX feedback? If I were to replace the old version with the latest update today, unless there was something drastic, I very likely can't tell the difference.

**Comment by alphapapa** [comment]
@whacked No problem, I appreciate your checking in anyway.  :)  Yes, I'm looking for general feedback and testing.  The new `helm-org-rifle-occur` commands operate differently, showing results in a persistent buffer instead of a Helm buffer.  Seems to be working well, so I went ahead and pushed it to master, but I'd appreciate any feedback you may have.

The timestamp-sorting branch (not yet in master or MELPA) lets you run the commands with a universal prefix and choose a sorting method.  I think it's working fine, but since it has some significant changes in the code, I'd like to get a little feedback from someone else before I push it out as a stable version.

**Comment by zeltak** [comment]
thx @alphapapa 

I in contrast to @whacked  use org rifle daily 😁

I had a crazy busy week but if its pushed to MELPA i will try it this week and report back ASAP

thx again for this awesome package ;-)

z

**Comment by alphapapa** [comment]
I pushed the branch to master, so I'll go ahead and close this, but please let me know if you have any feedback.  :)
