### ISSUE TITLE
Symbol’s function definition is void: helm-org-rifle--show-marked-entries

### ISSUE THREAD

**Issue by timmli** [alphapapa/helm-org-rifle#14]
I have no luck when trying to go to a search hit in `helm-org-rifle` (by pressing return). The following message appears:

> Symbol’s function definition is void: helm-org-rifle--show-marked-entries

This is with version 20170406.2149.

**Comment by alphapapa** [comment]
Sorry about that!  I renamed the function but somehow missed changing the symbol in the action list.  Thank you for reporting!
