### ISSUE TITLE
Please test new helm-org-rifle-occur code

### ISSUE THREAD

**Issue by alphapapa** [alphapapa/helm-org-rifle#17]
@zeltak Hey Z, how are you my friend.  :)  If you have time, I'd appreciate it if you could test the latest version (should be on MELPA later today).  I've improved the `helm-org-rifle-occur` commands so that headers and separators are displayed between sources and results, and you can collapse/fold each result separately (instead of the way it incorrectly folded across result boundaries before), and you can collapse all the results in each source.  This ends up being sort of like `org-sparse-tree` but for multiple files at once.

Thanks for your help!

**Comment by zeltak** [comment]
sure! would be happy to test today as soon as its on MELPA

best

Z

**Comment by zeltak** [comment]
Hi

this is really cool!

i played around with it today and didnt find any problems!

only suggestion (which is really not that big) is perhaps have the differentiation line between files have a more visible color

thx alot!

Z

**Comment by alphapapa** [comment]
Hey Z, thanks a lot for the feedback.  Could you send me a screenshot of what the colors look like with your theme, or let me know which theme you're using if it's on MELPA?  The color is the `helm-header` color, which I think you can customize in Helm itself.

**Comment by alphapapa** [comment]
Hey Z,

I made some changes to the occur code a while back, and the results should be more separated visually.  Could you let me know what you think?

Thanks.

**Comment by zeltak** [comment]
ofc would be happy to! i cant see any updates on Melpa so remind me how to test it again?

Z

**Comment by alphapapa** [comment]
Actually the changes were made several weeks ago, at least, so the current MELPA version already has them.  Just run `helm-org-rifle-occur`, etc.  Thanks!

**Comment by zeltak** [comment]
Hi again!

had some time today from crazy work schedule to thoroughly test helm-org-rifle-occur. 
it works great now and really like the visual separator (though i will need to explore how to change the color in the helm config since it look atrocious here :) )

thx again, happy to test anything else needed

Z

**Comment by alphapapa** [comment]
Great, thanks, Z!  Yeah, I don't know what to do about the separator, it doesn't look good on my theme either.  Let me know if you come up with something that looks good.  :)

BTW, did you see org-super-agenda?
