### ISSUE TITLE
Long Paths are Cut Off in Helm Preview?

### ISSUE THREAD

**Issue by georgewsinger** [alphapapa/helm-org-rifle#18]
I am using `helm-org-rifle` with spacemacs running helm. I also have `helm-org-rifle-show-path` set to `t`. Everything works great, except that longer org-mode paths are being heavily truncated in the display (even though it looks like there should be plenty of room to show the longer org-mode paths).

Is there a way to prevent this from happening?

**Comment by alphapapa** [comment]
Hi George,

Can you show me a screenshot?  I don't use Spacemacs regularly, although I try it out now and then.  I don't recall seeing this problem before, but it's possible that something in Spacemacs is breaking it now.

Thanks.

**Comment by alphapapa** [comment]
I'm going to close this now, but feel free to reopen if you need to.
