### ISSUE TITLE
Searching by Path?

### ISSUE THREAD

**Issue by georgewsinger** [alphapapa/helm-org-rifle#19]
Say I have

```
* Parent
** Child
** Grandchild <--I want to be here
```

and

```
* Heading
** Also With
*** Grandchild
```
I keep searching using `helm-org-rifle` by typing "Child/Grandchild" or "Child Grandchild" so that I can get to my desired location. But this doesn't seem to work with `helm-org-rifle`. Instead I can only type "Grandchild" and have to sift through the multiple results.

Is there a way around this?

**Comment by alphapapa** [comment]
Hi George,

This was a long-standing oversight on my part.  Thanks for noticing and bringing it to my attention.
