### ISSUE TITLE
Package broken on Melpa

### ISSUE THREAD

**Issue by adam52** [alphapapa/helm-org-rifle#23]
I did an Upgrade recently, of all my packages on Melpa. Now when I run `helm-org-rifle` I am prompted for a "PATTERN:" (which I key in) and I can then select a result in the indirect buffer. 

However, when I hit `[enter]` to complete the selection, I receive an error message:

    Wrong number of arguments: (1 . 1), 0

Any ideas?

Thanks,
-Adam

**Comment by adam52** [comment]
Thierry Volpiatto, who maintains the `helm` package, gave me this fix. In `helm-org-rifle.el` find this code:

      (helm-cleanup-hook (lambda ()
                           ;; Close new buffers if enabled
                           (when helm-org-rifle-close-unopened-file-buffers
                             (if (= 0 helm-exit-status)
                                 ;; Candidate selected; close other new buffers
                                 (let ((candidate-source (helm-attr 'name (helm-get-current-source))))
                                   (dolist (source (helm-get-sources))
                                     (unless (or (equal (helm-attr 'name source)
                                                        candidate-source)
                                                 (not (helm-attr 'new-buffer source)))
                                       (kill-buffer (helm-attr 'buffer source)))))
                               ;; No candidates; close all new buffers
                               (dolist (source (helm-get-sources))
                                 (when (helm-attr 'new-buffer source)
                                   (kill-buffer (helm-attr 'buffer source))))))))))

and replace both lines that say `(dolist (source (helm-get-sources))` with `(dolist (source helm-sources)`.

Here's the thread over on the helm page: [issue 2007](https://github.com/emacs-helm/helm/issues/2007#issuecomment-377012097).

**Comment by alphapapa** [comment]
Thanks for reporting and finding the fix!

**Comment by adam52** [comment]
No worries. Thank you!
