### ISSUE TITLE
Customize helm actions

### ISSUE THREAD

**Issue by hoelterhof** [alphapapa/helm-org-rifle#30]
Hello! Other helm-packages like helm-bbdb do offer the possibility to customize the actions. They do use variables like `helm-bbdb-actions`. Is it possible to customize the helm actions here? Can you include a variable like `helm-org-rifle-actions`? I would like to add lots of personal actions like copy the attachments directory to killring, add attachment, copy id to killring etc. Thank you and greetings, Tobias

**Comment by alphapapa** [comment]
Yes, as a matter of fact, please see https://github.com/alphapapa/helm-org-rifle/pull/28  :)
