### ISSUE TITLE
Searching through a narrowed buffer

### ISSUE THREAD

**Issue by akirak** [alphapapa/helm-org-rifle#31]
It seems that when a buffer is narrowed, helm-org-rifle does not display contents outside the narrowing target. I suppose this is not an expected behavior for file/directory rifle commands, and I think you can resolve this issue by using `org-with-wide-buffer` inside `helm-org-rifle--get-candidates-in-buffer`. However, there can be situations where users simply want to search contents inside the narrowed scope, e.g. the user is looking at a narrowed indirect buffer.

What do you think?

**Comment by alphapapa** [comment]
Hmm, I'm not sure about this.  I think it's generally best to obey narrowing unless there's a good reason to override it.  I've never needed it to work by widening, and I haven't had anyone mention it until now.  I can think of situations in which I would *not* want the buffer widened, e.g. I have a large file with subtrees, and I have the buffer narrowed to a project's subtree (probably in an indirect buffer), and then I want to use rifle to search in the subtree.  If it widened by default, I would get results for the whole buffer.  If I wanted to get results for the whole buffer, I would run the rifle command in the unnarrowed, direct buffer, or use a rifle command that searched all buffers.

What do you think?

**Comment by akirak** [comment]
You are probably right. If I need a narrowed view but still need to browse all headings with rifle, I'll create an indirect buffer. Thanks.
