### ISSUE TITLE
Rifle refile binding

### ISSUE THREAD

**Issue by holocronweaver** [alphapapa/helm-org-rifle#33]
Attempting to call this refile with `C-c C-w` produces a pop-up window called *helm-mode-org-refile* which seems to be the ordinary helm org refile, which requires typing the full name of the file and header exactly as shown without permitting spaces.

I figured this was due to something wonky with my keybindings, so I tried manually overriding the binding:
```
(define-key map (kbd "C-c C-w") #'helm-org-rifle--refile)
```
Using this binding results in an error message: `command-execute: Wrong type argument: commandp, helm-org-rifle--refile`

Any ideas what is going on? I'm not familiar with what the #' is meant to accomplish here, but I think it has to do with lambdas?

**Comment by holocronweaver** [comment]
Cool, just tested out your fix, seems to do the trick! 

This is probably the fastest bug fix response I have ever seen. Thanks allot. :smile:

**Comment by alphapapa** [comment]
Haha, well, you responded to the fix before I could thank you for it here.  Thank you very much.  That one has apparently been present for a while, but I guess not many people use `C-c C-w` to refile there, including myself, so it didn't get noticed.
