### ISSUE TITLE
Error searching in buffers with text before the first heading

### ISSUE THREAD

**Issue by jonmoore** [alphapapa/helm-org-rifle#5]
Thanks for a nice package.

When run in a buffer using [in-buffer settings](http://orgmode.org/manual/In_002dbuffer-settings.html)   helm-org-rifle-get-candidates-in-buffer encounters an error like the following

Debugger entered--Lisp error: (error "Before first headline at position 33 in buffer misc.org")
  signal(error ("Before first headline at position 33 in buffer misc.org"))
  error("Before first headline at position %d in buffer %s" 33 #<buffer misc.org>)
  byte-code("\300\301`p#\207" [error "Before first headline at position %d in buffer %s"] 4)
  org-back-to-heading(t)
  org-heading-components()

This can be fixed by adding 
```elisp
        (when (org-before-first-heading-p)
          (outline-next-heading))
```

after the call to ```(goto-char (point-min))``` on line 301.

**Comment by alphapapa** [comment]
I thought I remembered seeing this a few times, but it didn't seem to happen regularly.  I'll fix it soon.  Thanks for reporting it!
