### ISSUE TITLE
Not possible to move as always between the helm-org-rifle-agenda-files results

### ISSUE THREAD

**Issue by Ypot** [alphapapa/helm-org-rifle#84]
Lately, I can't move between the _helm-org-rifle-agenda-files_ results. 
The highlighting, using the movement keys, goes down, and then it jumps back up, but it never reaches the bottom.

For example, right now I can see 14 results that I can reach using the mouse, but I can just go to the first 5 results.

Meanwhile, results are separated in files, but it is not possible to jump from one file results to a different file results.

**Comment by alphapapa** [comment]
As you can see, nothing has changed in this repository for the last 4 months.  And other than the very minor fix applied then, nothing has changed since October of 2022.  So whatever problem you're having, it couldn't be a bug in this package.
